export default function AboutPage() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-12">
      <h2 className="font-display text-4xl text-chalk mb-2">About</h2>
      <p className="text-dust mb-10">How the PRA Predictor works.</p>

      <div className="space-y-8">
        <section className="bg-hardwood border border-sideline rounded-xl p-6">
          <h3 className="font-display text-xl text-gold mb-3">The Model</h3>
          <p className="text-chalk/80 text-sm leading-relaxed">
            Predictions are generated by an XGBoost regression model trained on multiple seasons of NBA game logs.
            The model predicts a player&apos;s Points + Rebounds + Assists (PRA) for their next game, then
            decomposes the total back into individual stat estimates.
          </p>
        </section>

        <section className="bg-hardwood border border-sideline rounded-xl p-6">
          <h3 className="font-display text-xl text-gold mb-3">Features Used</h3>
          <ul className="text-chalk/80 text-sm space-y-2">
            {[
              ["Rolling averages", "L3, L5, L10 game windows for PTS, REB, AST, and PRA"],
              ["Variability", "Standard deviation of PRA over last 5 games"],
              ["Rest", "Days since the player's last game"],
              ["Back-to-back", "Whether this is the second game in two nights"],
              ["Win streak", "Rolling wins over last 5 games"],
              ["Home/away", "Home court indicator"],
            ].map(([name, desc]) => (
              <li key={name} className="flex gap-3">
                <span className="text-gold font-mono font-bold shrink-0">{name}</span>
                <span className="text-dust">{desc}</span>
              </li>
            ))}
          </ul>
        </section>

        <section className="bg-hardwood border border-sideline rounded-xl p-6">
          <h3 className="font-display text-xl text-gold mb-3">Training Data</h3>
          <p className="text-chalk/80 text-sm leading-relaxed">
            The model is trained on game logs from the 2023-24, 2024-25, and 2025-26 NBA seasons across
            20+ players spanning guards, wings, and bigs. A chronological 70/15/15 train/validation/test
            split is used to prevent data leakage.
          </p>
        </section>

        <section className="bg-hardwood border border-sideline rounded-xl p-6">
          <h3 className="font-display text-xl text-gold mb-3">Prop Line Analyzer</h3>
          <p className="text-chalk/80 text-sm leading-relaxed">
            The analyzer compares the model&apos;s projection against a sportsbook-style line you set.
            Hit rate is calculated from the player&apos;s last 20 games. Context bullets highlight
            factors that are pushing the prediction up or down relative to season averages.
          </p>
        </section>

        <section className="bg-hardwood border border-sideline rounded-xl p-6">
          <h3 className="font-display text-xl text-gold mb-3">Disclaimer</h3>
          <p className="text-chalk/80 text-sm leading-relaxed">
            This tool is for informational and educational purposes only. Predictions are based on
            historical averages and machine learning estimates — they are not guarantees of future
            performance. Always gamble responsibly.
          </p>
        </section>
      </div>
    </main>
  );
}
